import { AchievementDefinition } from '../types/gamification.types';

export const ACHIEVEMENTS: Record<string, AchievementDefinition> = {
  FIRST_HABIT: {
    id: 'FIRST_HABIT',
    title: 'The Journey Begins',
    description: 'Complete your first habit.',
    icon: '🌱',
    tier: 'bronze',
    category: 'consistency',
    xpReward: 50,
    isHidden: false,
    target: 1,
  },
  STREAK_7: {
    id: 'STREAK_7',
    title: 'Momentum',
    description: 'Maintain a 7-day streak on any habit.',
    icon: '🔥',
    tier: 'silver',
    category: 'streaks',
    xpReward: 150,
    isHidden: false,
    target: 7,
  },
  STREAK_30: {
    id: 'STREAK_30',
    title: 'Unstoppable',
    description: 'Maintain a 30-day streak on any habit.',
    icon: '⚡',
    tier: 'gold',
    category: 'streaks',
    xpReward: 500,
    isHidden: false,
    target: 30,
  },
  STREAK_100: {
    id: 'STREAK_100',
    title: 'Century',
    description: 'Maintain a 100-day streak on any habit.',
    icon: '💯',
    tier: 'platinum',
    category: 'streaks',
    xpReward: 2000,
    isHidden: false,
    target: 100,
  },
  PERFECT_WEEK: {
    id: 'PERFECT_WEEK',
    title: 'Flawless Execution',
    description: 'Complete all scheduled habits for 7 consecutive days.',
    icon: '🎯',
    tier: 'gold',
    category: 'consistency',
    xpReward: 400,
    isHidden: false,
    target: 7,
  },
  EARLY_BIRD: {
    id: 'EARLY_BIRD',
    title: 'Early Riser',
    description: 'Complete a habit before 6:00 AM.',
    icon: '🌅',
    tier: 'silver',
    category: 'special',
    xpReward: 100,
    isHidden: false,
    target: 1,
  },
  NIGHT_OWL: {
    id: 'NIGHT_OWL',
    title: 'Midnight Oil',
    description: 'Complete a habit after 10:00 PM.',
    icon: '🦉',
    tier: 'silver',
    category: 'special',
    xpReward: 100,
    isHidden: false,
    target: 1,
  },
  // Secret/Hidden Achievements
  RECOVERY_MASTER: {
    id: 'RECOVERY_MASTER',
    title: 'Bounce Back',
    description: 'Recover a streak after missing a day.',
    icon: '🔄',
    tier: 'bronze',
    category: 'hidden',
    xpReward: 100,
    isHidden: true,
    target: 1,
  },
};
